[tool.black]
line-length = 119
target-version = ['py312']
include = '\.pyi?$'
extend-exclude = ''

[tool.isort]
profile = "black"
line_length = 119
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
