name: Builds the documentation

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pdoc3
          pip install -r requirements.txt

      - name: Generate API documentation with pdoc3
        run: |
          pdoc --html --force --output-dir labour-abm-canada-docs/docs/api labour_abm_canada

#      # Uncomment the following lines for the deployment of the MkDocs site
#      - name: Build and deploy MkDocs site
#        run: |
#          mkdocs gh-deploy --force
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}